IF  EXISTS (SELECT * FROM SYS.OBJECTS WHERE OBJECT_ID = OBJECT_ID(N'[GETNEWOUTBOUNDORDERS]') AND TYPE IN (N'P', N'PC'))
DROP PROCEDURE [GETNEWOUTBOUNDORDERS]
GO

SET ANSI_NULLS ON
GO

SET ANSI_PADDING ON
GO

SET ANSI_WARNINGS ON
GO

SET ARITHABORT ON
GO

SET CONCAT_NULL_YIELDS_NULL ON
GO

SET NUMERIC_ROUNDABORT OFF
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE PROCEDURE GETNEWOUTBOUNDORDERS
AS					   
BEGIN
	SET NOCOUNT ON;
	DECLARE
	@INTODATE DATETIME = DATEADD(DAY, -1, GETDATE()),
	@RECEIVETIME DATETIME = DATEADD(DAY, -1, GETDATE());
	SELECT TOP 1 @INTODATE=INTODATE FROM VMI_OUTBOUNDREPORT WITH(NOLOCK) WHERE SUCODE NOT IN ('CSC44453','CSC40467') ORDER BY INTODATE DESC;
	SELECT TOP 1 @RECEIVETIME=RECEIVETIME FROM VMI_OUTBOUNDREPORT WITH(NOLOCK) WHERE SUCODE IN ('CSC44453','CSC40467') ORDER BY RECEIVETIME DESC;

	INSERT INTO VMI_OUTBOUNDREPORT (ID, SLCODE, SHIPTITLE, SLAREA, SUPIN, SUCODE, STATUS, INTODATE, ADDTIME) 
	SELECT REPLACE (NEWID(), '-' , ''), SL.SLCODE, SL.SHIPTITLE, SL.SLAREA, SL.SUPIN, U.SUCODE, SL.STATUS, SL.INTODATE, GETDATE()
	FROM OSSHIPLIST_PRE SL WITH(NOLOCK)
	INNER JOIN OSSHIPUSER U WITH(NOLOCK) ON SL.SUPIN=U.SUPIN
	WHERE INTODATE>@INTODATE
	AND SUCODE NOT IN ('CSC44453','CSC40467');

	INSERT INTO VMI_OUTBOUNDREPORT (ID, REFVALUE, [RECEIVETIME], SUPIN, SUCODE, ADDTIME) 
	SELECT REPLACE (NEWID(), '-' , ''), REF_VALUE, RECEIVETIME, PIN, PARTNER, GETDATE()
	FROM API_BASRECEIVEJOB A WITH(NOLOCK)
	WHERE RECEIVETIME>@RECEIVETIME
	AND PARTNER IN ('CSC44453','CSC40467')
	AND TABLE_NAME IN ('WMS_CONSIGN_ORDER_NOTIFY', 'LOGISTICS_SKU_PAID');
END;
GO