IF  EXISTS (SELECT * FROM SYS.OBJECTS WHERE OBJECT_ID = OBJECT_ID(N'[GETNEWINBOUNDORDERS]') AND TYPE IN (N'P', N'PC'))
DROP PROCEDURE [GETNEWINBOUNDORDERS]
GO

SET ANSI_NULLS ON
GO

SET ANSI_PADDING ON
GO

SET ANSI_WARNINGS ON
GO

SET ARITHABORT ON
GO

SET CONCAT_NULL_YIELDS_NULL ON
GO

SET NUMERIC_ROUNDABORT OFF
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE PROCEDURE GETNEWINBOUNDORDERS
AS					   
BEGIN
	SET NOCOUNT ON;
	DECLARE
	@STARTTIME DATETIME = DATEADD(DAY, -1, GETDATE());
	SELECT TOP 1 @STARTTIME=RECEIVETIME FROM VMI_INBOUNDREPORT ORDER BY RECEIVETIME DESC;

	INSERT INTO VMI_INBOUNDREPORT (ID, REF_VALUE, PARTNER, SLAREA, PIN, RECEIVETIME, PARSESTATUS, POSTFLUX, SEFLAG, LOTNO, ADDTIME) 

	SELECT REPLACE (NEWID(), '-' , ''), A.REF_VALUE, A.PARTNER, B.SGAREA, A.PIN, A.RECEIVETIME
	, C.STATUS, B.POSTFLUX, B.SEFLAG, B.LOTNO, GETDATE()
	FROM API_BASRECEIVEJOB A WITH(NOLOCK)
	LEFT JOIN OSSHIPNOTICE B WITH(NOLOCK) ON(A.REF_VALUE=B.LOTNO)
	LEFT JOIN VMI_MESSAGEPARSERECORD C WITH(NOLOCK) ON(A.JOBID=C.JOBID)
	WHERE A.RECEIVETIME>@STARTTIME
	AND A.PARTNER IN ('CSC44453', 'CSC40467')
	AND A.TABLE_NAME IN ('WMS_STOCK_IN_ORDER_NOTIFY', 'LOGISTICS_SKU_STOCKIN_INFO')
	UNION ALL
	SELECT REPLACE (NEWID(), '-' , ''), LOTNO, SUCODE, SGAREA, '', OPTIME
	, '', POSTFLUX, SEFLAG, LOTNO, GETDATE()
	FROM OSSHIPNOTICE WITH(NOLOCK)
	WHERE OPTIME>@STARTTIME AND SUCODE NOT IN ('CSC44453', 'CSC40467')
END;
GO