IF  EXISTS (SELECT * FROM SYS.OBJECTS WHERE OBJECT_ID = OBJECT_ID(N'UPDATEOUTBOUNDREPORT') AND TYPE IN (N'P', N'PC'))
DROP PROCEDURE UPDATEOUTBOUNDREPORT
GO

SET ANSI_NULLS ON
GO

SET ANSI_PADDING ON
GO

SET ANSI_WARNINGS ON
GO

SET ARITHABORT ON
GO

SET CONCAT_NULL_YIELDS_NULL ON
GO

SET NUMERIC_ROUNDABORT OFF
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE PROCEDURE UPDATEOUTBOUNDREPORT
AS					   
BEGIN
	SET NOCOUNT ON;
	DECLARE
	@ID VARCHAR(50),
	@SHIPTITLE NVARCHAR(500),
	@SLAAECODE VARCHAR(40),
	@SLDATE SMALLDATETIME,
	@STATUS CHAR(1),
	@SLFLAG INT,
	@NEWORDER CHAR(1),
	@SHIPWEIGHT DECIMAL(10,3)=0,
	@ISPAYMENT CHAR(1),
	@ISPACKED CHAR(1),
	@PACKEDTIME DATETIME = NULL,
	@PACKEDWEIGHT NUMERIC(18,2)=0,
	@ISCZ CHAR(1),
	@CZTIME DATETIME = NULL,
	@CZWEIGHT NUMERIC(10,3)=0,
	@REALWEIGHT NUMERIC(10,3)=0,
	@CHARGEWEIGHT NUMERIC(10,3)=0,
	@ISOUTBOUND CHAR(1),
	@OUTBOUNDTIME DATETIME = NULL,
	@OUTBOUNDWEIGHT NUMERIC(18,2)=0;

	DECLARE REPORT_CURSOR CURSOR LOCAL FOR
	SELECT ID, SHIPTITLE, STATUS, ISNULL(SLFLAG, 0), ISNULL(NEWORDER,'Y'), ISNULL(ISPACKED, 'N'), ISNULL(ISCZ, 'N'), ISNULL(ISPAYMENT, 'N'), ISNULL(ISOUTBOUND, 'N') FROM VMI_OUTBOUNDREPORT WITH(NOLOCK) WHERE STATUS<>'C' AND ISNULL(SLFLAG, 0)<>4 ORDER BY INTODATE
	OPEN REPORT_CURSOR
	FETCH FROM REPORT_CURSOR INTO @ID, @SHIPTITLE, @STATUS, @SLFLAG, @NEWORDER, @ISPACKED, @ISCZ, @ISPAYMENT, @ISOUTBOUND;
	WHILE @@FETCH_STATUS=0
	BEGIN
	 IF @STATUS <> '1'
		BEGIN
			SELECT @STATUS=STATUS FROM OSSHIPLIST_PRE WITH(NOLOCK) WHERE SHIPTITLE=@SHIPTITLE;
		END
	 IF @STATUS = '1'
		BEGIN
			SELECT @NEWORDER=NEWORDER, @SLFLAG=SLFLAG, @SLAAECODE=SLAAECODE, @SLDATE=SLDATE FROM OSSHIPLIST WITH(NOLOCK) WHERE SHIPTITLE=@SHIPTITLE;
			IF @NEWORDER = 'N'
			BEGIN
				IF @ISPACKED = 'N'--打包
				BEGIN
					SELECT @PACKEDTIME=GMT_SEND, @PACKEDWEIGHT=WEIGHT FROM API_STOCKOUT WITH(NOLOCK) WHERE SHIPORDER_ID=@SHIPTITLE AND  STATUS='PACKED';
					IF @PACKEDTIME IS NULL
					BEGIN
						GOTO DOUPDATE
					END
					IF @PACKEDTIME IS NOT NULL
					BEGIN
						SET @ISPACKED = 'Y';
					END
				END
				IF @ISCZ = 'N'--称重
				BEGIN
					SELECT @CZTIME=GMT_SEND, @CZWEIGHT=WEIGHT FROM API_STOCKOUT WITH(NOLOCK) WHERE SHIPORDER_ID=@SHIPTITLE AND  STATUS='1';
					IF @CZTIME IS NULL
					BEGIN
						GOTO DOUPDATE
					END
					IF @CZTIME IS NOT NULL
					BEGIN
						SET @ISCZ = 'Y';
					END
				END
				IF @ISPAYMENT = 'N'--扣款
				BEGIN
					SELECT @ISPAYMENT=ISPAYMENT, @SHIPWEIGHT=SLSHIPLBS FROM OSSHIPLIST WITH(NOLOCK) WHERE SHIPTITLE=@SHIPTITLE;
					IF @ISPAYMENT = 'N'
					BEGIN
						GOTO DOUPDATE
					END
				END
				IF @ISOUTBOUND = 'N'--出库
				BEGIN
					SELECT @OUTBOUNDTIME=GMT_SEND, @OUTBOUNDWEIGHT=WEIGHT FROM API_STOCKOUT WITH(NOLOCK) WHERE SHIPORDER_ID=@SHIPTITLE AND  STATUS='2';
					IF @OUTBOUNDTIME IS NULL
					BEGIN
						GOTO DOUPDATE
					END
					IF @OUTBOUNDTIME IS NOT NULL
					BEGIN
						SET @ISOUTBOUND = 'Y';
					END
				END
			END
		END

DOUPDATE:
	UPDATE VMI_OUTBOUNDREPORT SET STATUS=@STATUS, NEWORDER=@NEWORDER, ISPAYMENT=@ISPAYMENT
	,SLAAECODE=@SLAAECODE, SLDATE=@SLDATE, SLFLAG=@SLFLAG
	,SHIPWEIGHT=@SHIPWEIGHT, ISPACKED=@ISPACKED, PACKEDTIME=@PACKEDTIME, PACKEDWEIGHT=@PACKEDWEIGHT
	,ISCZ=@ISCZ, CZTIME=@CZTIME, CZWEIGHT=@CZWEIGHT
	,REALWEIGHT=@REALWEIGHT, CHARGEWEIGHT=@CHARGEWEIGHT
	,ISOUTBOUND=@ISOUTBOUND, OUTBOUNDTIME=@OUTBOUNDTIME, OUTBOUNDWEIGHT=@OUTBOUNDWEIGHT
	WHERE ID=@ID;

	FETCH FROM REPORT_CURSOR INTO @ID, @SHIPTITLE, @STATUS, @SLFLAG, @NEWORDER, @ISPACKED, @ISCZ, @ISPAYMENT, @ISOUTBOUND;
	END
CLOSE REPORT_CURSOR
DEALLOCATE REPORT_CURSOR;
END;
GO