IF  EXISTS (SELECT * FROM SYS.OBJECTS WHERE OBJECT_ID = OBJECT_ID(N'UPDATEINBOUNDREPORT') AND TYPE IN (N'P', N'PC'))
DROP PROCEDURE UPDATEINBOUNDREPORT
GO

SET ANSI_NULLS ON
GO

SET ANSI_PADDING ON
GO

SET ANSI_WARNINGS ON
GO

SET ARITHABORT ON
GO

SET CONCAT_NULL_YIELDS_NULL ON
GO

SET NUMERIC_ROUNDABORT OFF
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE PROCEDURE UPDATEINBOUNDREPORT
AS					   
BEGIN
	SET NOCOUNT ON;
	DECLARE
	@ID [VARCHAR](50),
	@REF_VALUE VARCHAR(50),
	@PARTNER VARCHAR(50),
	@SGAREA VARCHAR(50),
	@PARSESTATUS VARCHAR(1),
	@POSTFLUX INT=0,
	@SEFLAG INT;

	DECLARE REPORT_CURSOR CURSOR LOCAL FOR
	SELECT ID, REF_VALUE, PARTNER, PARSESTATUS, ISNULL(POSTFLUX,0), SEFLAG FROM VMI_INBOUNDREPORT WHERE ISNULL(PARSESTATUS,'')<>'N' AND (SEFLAG=0 OR SEFLAG=1) AND PARTNER ='CSC44453' UNION ALL
	SELECT ID, REF_VALUE, PARTNER, PARSESTATUS, ISNULL(POSTFLUX,0), SEFLAG FROM VMI_INBOUNDREPORT WHERE ISNULL(LOTNO,'')<>'' AND (SEFLAG=0 OR SEFLAG=1) AND PARTNER <>'CSC44453'
	OPEN REPORT_CURSOR
	FETCH FROM REPORT_CURSOR INTO @ID, @REF_VALUE, @PARTNER, @PARSESTATUS, @POSTFLUX, @SEFLAG;
	WHILE @@FETCH_STATUS=0
	BEGIN
	 IF @PARTNER = 'CSC44453'
	 BEGIN
		 IF @PARSESTATUS = 'P'
			BEGIN
				SELECT @PARSESTATUS=ISNULL(STATUS,'') FROM VMI_MESSAGEPARSERECORD WITH(NOLOCK) WHERE REF_VALUE=@REF_VALUE;
			END
		 IF @PARSESTATUS = 'Y'
			BEGIN
				IF @POSTFLUX=0
				BEGIN
					SELECT @POSTFLUX=ISNULL(POSTFLUX,0), @SGAREA=SGAREA FROM OSSHIPNOTICE WHERE LOTNO=@REF_VALUE;
				END

				SELECT @SEFLAG=SEFLAG FROM OSSHIPNOTICE WHERE LOTNO=@REF_VALUE;
				UPDATE VMI_INBOUNDREPORT SET PARSESTATUS=@PARSESTATUS, POSTFLUX=@POSTFLUX, SEFLAG=@SEFLAG, slArea=@SGAREA
				WHERE ID=@ID;
			END
	END
	IF @PARTNER <> 'CSC44453'
	BEGIN
		IF @POSTFLUX=0
		BEGIN
			SELECT @POSTFLUX=ISNULL(POSTFLUX,0) FROM OSSHIPNOTICE WHERE LOTNO=@REF_VALUE;
		END

		SELECT @SEFLAG=SEFLAG FROM OSSHIPNOTICE WHERE LOTNO=@REF_VALUE;
		UPDATE VMI_INBOUNDREPORT SET POSTFLUX=@POSTFLUX, SEFLAG=@SEFLAG
		WHERE ID=@ID;
	END

	FETCH FROM REPORT_CURSOR INTO @ID, @REF_VALUE, @PARTNER, @PARSESTATUS, @POSTFLUX, @SEFLAG;
	END
CLOSE REPORT_CURSOR
DEALLOCATE REPORT_CURSOR;
END;
GO